name: Deploy FastAPI Calculator

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirement.txt

      - name: Run Deployment Script
        run: .\deploy.bat
 
